name: Update Submodules

on:
  workflow_dispatch: # 수동 실행
  schedule:
    - cron: "0 0 * * *" # 매일 자정 자동 실행

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update submodules to latest commits
        run: |
          git submodule update --remote --recursive
          git add .
          git commit -m "feat: Update submodules to latest commits"
          git push origin main
